# Generated by Django 3.2 on 2021-08-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
