# Generated by Django 3.2 on 2021-08-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_alter_food_food_name'),
        ('recipe', '0002_alter_food_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diet.food')),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
