# Generated by Django 3.2 on 2021-08-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210812_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='food',
        ),
    ]
