# Generated by Django 3.2.5 on 2021-07-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplanner',
            old_name='food_id',
            new_name='foods',
        ),
        migrations.RenameField(
            model_name='mealplanner',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='food',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='diet.FoodHashtag'),
        ),
    ]
