# Generated by Django 3.2.5 on 2021-07-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_auto_20210721_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
