# Generated by Django 3.2.3 on 2021-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
