# Generated by Django 3.2.6 on 2021-08-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210803_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='닉네임을 입력해주세요', max_length=15),
        ),
    ]
