# Generated by Django 3.2.6 on 2021-08-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210812_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_table',
        ),
    ]
