# Generated by Django 3.2.6 on 2021-08-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210812_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default='undefine@example.com', max_length=128),
            preserve_default=False,
        ),
    ]
